server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
    connection-timeout: 1800000 # 30 minutos en milisegundos
    max-parameter-count: 10000

spring:
  mvc:
    problemdetails:
      enabled: true
  jackson.serialization:
    write-dates-as-timestamps: true

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10500MB

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}

    hikari:
      # Pool sizing - Más conservador para evitar saturación
      maximum-pool-size: ${MAX_SESSIONS:20}
      minimum-idle: ${MIN_IDLE:5}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: ${MAIL_HOST:smtppro.zoho.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USER:contacto@focuscomex.cl}
    password: ${MAIL_PWD:TU3wbiTVg9ny}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        from: ${MAIL_FROM:FocusComex <contacto@focuscomex.cl>}

api:
  rate-limit:
    capacity: 20
    time-window: 1
    time-unit: MINUTES
  frontend-url: ${APP_BASE_URL:http://localhost:3000}
  reset-password:
    token-expiration: 86400  # 24 horas en segundos
    path: "/restablecer-clave"

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_REDIRECT_URI:}

mercadopago:
  checkount:
    access-token: ${MERCADOPAGO_CHE_ACCESS_TOKEN}
  subs:
    access-token: ${MERCADOPAGO_SUB_ACCESS_TOKEN}
